version: '3.8'
name: 'drop-in-docker-php'
services:
 mysql:
  image: mysql:8.0.33
  env_file:
   - ./env/mysql.env
  ports:
   - $MYSQL_PORT:3306
  volumes:
   - ./vols/mysql/data/:/var/lib/mysql/
  user: $UID:$UID
 adminer:
  image: adminer:4.8.1-standalone
  env_file:
   - ./env/adminer.env
  ports:
   - $ADMINER_PORT:8080
 mailhog:
  image: mailhog/mailhog:v1.0.1
  ports:
   - $MAILHOG_SMTP_PORT:1025
   - $MAILHOG_UI_PORT:8025
 app:
  image: $APP_IMAGE
  build:
   context: .
   dockerfile: ./Dockerfiles/app.Dockerfile
   args:
    UID: $UID
  volumes:
   - $APP_VOLUMES_SRC:/var/www/html/
   - ./vols/app/docker-user-home/:/home/www-data/
  env_file:
   - ./env/app.env
 static:
  image: nginx:1.24.0-alpine3.17
  volumes:
   - $STATIC_VOLUMES_PUBLIC:/usr/share/nginx/html/
 proxy:
  image: $PROXY_IMAGE
  build:
   context: .
   dockerfile: ./Dockerfiles/proxy.Dockerfile
  ports:
   - $PROXY_PORT:80
  env_file:
    - ./env/proxy.env
